/** Static MCP tool catalog for UI / assistant (mirrors src/mcp.ts). */
export const MCP_TOOL_CATALOG: Array<{ name: string; description: string }> = [
  { name: "list_bases", description: "列出当前账号可见的多维表格和数据表" },
  { name: "whoami", description: "当前 MCP 身份" },
  { name: "get_limits", description: "查看常见上限" },
  { name: "create_base", description: "新建空多维表格" },
  { name: "rename_base", description: "重命名多维表格（需 owner）" },
  { name: "delete_base", description: "删除多维表格（需 owner）" },
  { name: "create_base_from_template", description: "从模板新建（requirements / engineering / todos / research）" },
  { name: "list_templates", description: "列出模板" },
  { name: "get_table", description: "读取表字段、视图与记录" },
  { name: "query_records", description: "按字段筛选排序记录" },
  { name: "create_table", description: "在 base 中新建数据表" },
  { name: "rename_table", description: "重命名数据表" },
  { name: "delete_table", description: "删除数据表（需 owner）" },
  { name: "create_field", description: "新建字段" },
  { name: "update_field", description: "更新字段（改名/选项/公式等）" },
  { name: "delete_field", description: "删除字段" },
  { name: "list_field_change_targets", description: "列出字段可变更的目标类型" },
  { name: "change_field_type", description: "更改字段类型并转换已有值" },
  { name: "create_record", description: "新建记录" },
  { name: "update_record", description: "更新记录" },
  { name: "delete_record", description: "删除记录" },
  { name: "create_view", description: "新建视图" },
  { name: "update_view", description: "更新视图配置" },
  { name: "delete_view", description: "删除视图" },
  { name: "set_view_protection", description: "设置视图保护 public/locked/personal" },
  { name: "export_csv", description: "导出 CSV" },
  { name: "import_csv", description: "导入 CSV" },
  { name: "list_comments", description: "列出记录评论" },
  { name: "add_comment", description: "添加评论" },
  { name: "delete_comment", description: "删除评论" },
  { name: "list_record_history", description: "记录变更历史" },
  { name: "watch_record", description: "关注记录" },
  { name: "unwatch_record", description: "取消关注" },
  { name: "is_watching_record", description: "是否关注" },
  { name: "list_watched_records", description: "我关注的记录" },
  { name: "create_record_share", description: "单记录分享链接" },
  { name: "get_shared_record", description: "用 token 读分享记录" },
  { name: "list_automations", description: "列出自动化" },
  { name: "create_automation", description: "创建自动化（含 schedule/webhook/button 等）" },
  { name: "update_automation", description: "更新自动化" },
  { name: "delete_automation", description: "删除自动化" },
  { name: "run_due_automations", description: "跑到期定时自动化（admin）" },
  { name: "get_acl", description: "读取行列权限（owner）" },
  { name: "set_acl", description: "设置行列权限（owner）" },
  { name: "preview_acl", description: "预览成员可见范围（owner）" },
  { name: "list_members", description: "列出 base 成员" },
  { name: "share_base", description: "分享给成员" },
  { name: "remove_member", description: "移除成员（owner）" },
  { name: "get_base_settings", description: "读取时区与门户配置" },
  { name: "set_base_settings", description: "更新时区/门户/飞书机器人（owner）" },
  { name: "send_feishu", description: "向飞书自定义机器人发文本" },
  { name: "send_feishu_digest", description: "推送即将到期的待办摘要到飞书" },
  { name: "create_calendar_feed", description: "创建 ICS 日历订阅" },
  { name: "list_calendar_feeds", description: "列出 ICS 日历订阅" },
  { name: "get_detail_page", description: "读取详情页布局" },
  { name: "set_detail_page", description: "设置详情页布局" },
  { name: "list_dashboards", description: "列出仪表盘" },
  { name: "create_dashboard", description: "创建仪表盘" },
  { name: "get_dashboard", description: "读取仪表盘聚合（可带切片器）" },
  { name: "update_dashboard", description: "更新仪表盘" },
  { name: "list_public_shares", description: "列出公开分享" },
  { name: "create_public_share", description: "创建公开分享" },
  { name: "set_public_share_enabled", description: "启用/关闭公开分享" },
  { name: "delete_public_share", description: "删除公开分享" },
  { name: "click_button", description: "点击按钮字段" },
  { name: "list_notifications", description: "列出通知" },
  { name: "mark_notification_read", description: "通知标为已读" },
  { name: "list_workflows", description: "列出工作流" },
  { name: "create_workflow", description: "创建工作流" },
  { name: "update_workflow", description: "更新工作流" },
  { name: "delete_workflow", description: "删除工作流" },
  { name: "list_workflow_runs", description: "列出审批运行" },
  { name: "get_workflow_run", description: "审批运行详情" },
  { name: "get_workflow_sla", description: "审批 SLA 概览" },
  { name: "process_workflow_timeouts", description: "处理审批超时（admin）" },
  { name: "decide_workflow_run", description: "审批通过/拒绝" },
  { name: "transfer_workflow_run", description: "转交审批" },
  { name: "add_sign_workflow_run", description: "加签" },
  { name: "list_workflow_audit", description: "工作流审计" },
  { name: "list_approval_proxies", description: "我的审批代理规则" },
  { name: "set_approval_proxy", description: "设置审批代理人" },
  { name: "clear_approval_proxy", description: "清除审批代理" },
  { name: "list_sync_jobs", description: "列出同步任务" },
  { name: "create_sync_job", description: "创建同步任务" },
  { name: "update_sync_job", description: "更新同步任务" },
  { name: "run_sync_job", description: "执行同步任务" },
  { name: "delete_sync_job", description: "删除同步任务" },
  { name: "list_plugin_hooks", description: "列出插件钩子" },
  { name: "create_plugin_hook", description: "创建插件钩子（admin）" },
  { name: "update_plugin_hook", description: "更新插件钩子（admin）" },
  { name: "delete_plugin_hook", description: "删除插件钩子（admin）" },
  { name: "list_marketplace_plugins", description: "插件市场与最近事件" },
  { name: "set_marketplace_plugin", description: "启停市场插件（admin）" },
  { name: "upload_file", description: "上传附件（base64，≤8MB）" },
  { name: "get_upload_meta", description: "附件元信息" },
  { name: "delete_upload", description: "删除附件" },
];
